// Copies the logos in brand/ into src/views/brands.ts as inline SVG markup
// (run by hand: node scripts/gen-brands.mjs). The app never reads brand/.
import { readFileSync, writeFileSync } from "node:fs";
const map = { "3CX": "integration_3cx", Claude: "integration_claude", github: "integration_github", n8n: "integration_n8n",
  notion: "integration_notion", outlook: "integration_outlook", resend: "integration_resend", stripe: "integration_stripe",
  vercel: "integration_vercel", zammad: "integration_zammad" };
let out = `// Brand logos of the integrations, copied from the SVGs in brand/ (the folder
// is only the source: nothing reads it at run time). Dark marks use
// currentColor so they stay visible on the island's dark background.
// Generated by scripts/gen-brands.mjs: rerun it when a logo changes.

export const BRAND_SVG: Record<string, string> = {\n`;
for (const [file, id] of Object.entries(map)) {
  let s = readFileSync(`brand/${file}.svg`, "utf8");
  // <style> classes → fill attributes
  const cls = {};
  for (const m of s.matchAll(/\.([\w-]+)\s*\{\s*fill:\s*([^;]+);/g)) cls[m[1]] = m[2].trim();
  s = s.replace(/<\?xml[^>]*\?>/g, "").replace(/<!--[\s\S]*?-->/g, "").replace(/<defs>[\s\S]*?<\/defs>/g, "")
    .replace(/<title>[\s\S]*?<\/title>/g, "").replace(/<desc>[\s\S]*?<\/desc>/g, "")
    .replace(/class="([^"]*)"/g, (_, c) => { const f = c.split(/\s+/).map((k) => cls[k]).find(Boolean); return f ? `fill="${f}"` : ""; })
    .replace(/\s(width|height|id|data-name|data-v-[\w-]+|sketch:type|xmlns:\w+|version|preserveAspectRatio)="[^"]*"/g, "")
    .replace(/fill="(#000000|#000|black|#0F0F0F)"/gi, 'fill="currentColor"')
    .replace(/\s+/g, " ").replace(/>\s+</g, "><").trim();
  // The drawing's own bounds (measured in the browser): no empty margins.
  const crop = { integration_3cx: "36 318 887 323", integration_outlook: "170 90 220 220",
    integration_resend: "450 450 900 900", integration_stripe: "0 0 512 213" }[id];
  if (crop) s = s.replace(/viewBox="[^"]*"/, `viewBox="${crop}"`);
  out += `  ${id}: ${JSON.stringify(s)},\n`;
}
out += "};\n";
writeFileSync("src/views/brands.ts", out);
